yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/',
         views.add_comment,
         name='add_comment',
         ),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path('likes/', views.likes_index, name='likes_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
    path(
        'posts/<int:post_id>/like/',
        views.like,
        name='post_like'
    ),
    path(
        'posts/<int:post_id>/unlike/',
        views.unlike,
        name='post_unlike'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('', include('posts.urls', namespace='posts')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import (GenericForeignKey,
                                                GenericRelation)
from django.contrib.contenttypes.models import ContentType
from django.db import models

User = get_user_model()
TITLE_CHAR_COUNT: int = 15


class Group(models.Model):
    """
    Модель группы.

    :param title: Название группы.
    :param slug: Уникальный идентификатор группы.
    :param description: Описание группы.
    """
    title = models.CharField(verbose_name='Название', max_length=200)
    slug = models.SlugField(verbose_name='Линк', unique=True)
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        """
        Возвращает строковое представление модели.

        :return: Название группы.
        """
        return f'{self.title}'


class Like(models.Model):
    """
    Модель лайка пользователем поста.

    :param user: Пользователь, который поставил лайк под постом.
    :param content_type:
    :param object_id:
    :param content_object:
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='likes',
        verbose_name='Пользователь',
    )
    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(
        'content_type',
        'object_id',
    )

    def __str__(self):
        return (
            f'{self.user} лайкнул '
            f'{self.content_type} {self.object_id} "{self.content_object}"'
        )


class Post(models.Model):
    """
    Модель поста.

    :param text: Текст поста.
    :param pub_date: Дата и время публикации.
    :param author: Автор поста.
    :param group: Группа, к которой относится пост.
    :param image: Изображение, прикрепленное к посту.
    """
    text = models.TextField(
        verbose_name='Текст',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        blank=True,
        null=True,
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
    )
    likes = GenericRelation(Like)

    def __str__(self):
        """
        Возвращает строковое представление модели.

        :return: Текст поста.
        """
        return f'{self.text[:TITLE_CHAR_COUNT] + "..."}'

    class Meta:
        ordering = ('-pub_date',)

    @property
    def total_likes(self):
        return self.likes.count()


class Comment(CreatedModel):
    """
    Модель комментария.

    :param post: Пост, к которому оставлен комментарий.
    :param author: Автор комментария.
    :param text: Текст комментария.
    """
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
    )
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст нового комментария',
    )

    def __str__(self):
        """
        Возвращает строковое представление модели.

        :return: Текст комментария.
        """
        return f'{self.text[:TITLE_CHAR_COUNT] + "..."}'


class Follow(models.Model):
    """
    Модель подписки пользователя на автора.

    :param user: Пользователь, который подписывается на автора.
    :param author: Автор, на которого подписывается пользователь.
    """
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор',
    )

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']
        labels = {
            'text': 'Введите текст поста:',
            'group': 'Укажите подходящую группу:',
        }
        help_texts = {
            'group': 'Можете указать тематику поста или оставить поле пустым'
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post
from .services import add_like, is_liked, remove_like

POST_PER_PAGE: int = 10

User = get_user_model()


def make_paginator(request, post_list):
    """
    Функция для создания объекта пагинатора.

    Аргументы:
    - request (HttpRequest): объект запроса
    - post_list (QuerySet): список постов

    Возвращает:
    - Page: объект страницы пагинации
    """
    paginator = Paginator(post_list, POST_PER_PAGE)
    page_number = request.GET.get('page')
    return paginator.get_page(page_number)


@cache_page(20)
def index(request):
    """
    Класс представления главной страницы.

    Аргументы:
    - request (HttpRequest): объект запроса

    Возвращает:
    - HttpResponse: ответ с отображением страницы
    """
    page_obj = make_paginator(
        request,
        Post.objects.select_related('group', 'author').all(),
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """
    Класс представления страницы со списком постов в группе.

    Аргументы:
    - request (HttpRequest): объект запроса
    - slug (str): уникальный идентификатор группы

    Возвращает:
    - HttpResponse: ответ с отображением страницы
    """
    group = get_object_or_404(Group, slug=slug)
    page_obj = make_paginator(
        request,
        group.posts.select_related('author').all(),
    )
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """
    Класс представления страницы профиля пользователя.

    Аргументы:
    - request (HttpRequest): объект запроса
    - username (str): имя пользователя

    Возвращает:
    - HttpResponse: ответ с отображением страницы
    """
    author = get_object_or_404(User, username=username)
    page_obj = make_paginator(
        request,
        author.posts.select_related('group').all()
    )
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=author,
    ).exists()
    context = {'page_obj': page_obj,
               'author': author,
               'following': following,
               }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """
    Класс представления страницы поста.

    Аргументы:
    - request (HttpRequest): объект запроса
    - post_id (int): идентификатор поста

    Возвращает:
    - HttpResponse: ответ с отображением страницы
    """
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm()
    comments = post.comments.all()
    post_is_liked = is_liked(post, request.user)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
        'post_id': post_id,
        'post_is_liked': post_is_liked,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """
    Класс представления страницы создания поста.

    Аргументы:
    - request (HttpRequest): объект запроса

    Возвращает:
    - HttpResponse: ответ с отображением страницы
    """
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if form.is_valid():
        author = request.user
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', author.username)
    context = {
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    """
    Класс представления страницы редактирования поста.

    Аргументы:
    - request (HttpRequest): объект запроса
    - post_id (int): идентификатор поста

    Возвращает:
    - HttpResponse: ответ с отображением страницы
    """
    edit_post = get_object_or_404(Post, id=post_id)
    if request.user != edit_post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=edit_post,
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {'form': form,
               'is_edit': True,
               'post_id': post_id,
               }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    page_obj = make_paginator(
        request,
        Post.objects.filter(author__following__user=request.user).all(),
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def likes_index(request):
    page_obj = make_paginator(
        request,
        Post.objects.filter(likes__user=request.user).all(),
    )
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/like.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    follower = Follow.objects.filter(user=request.user, author=author)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username=author)


@login_required
def like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    add_like(post, request.user)
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def unlike(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    remove_like(post, request.user)
    return redirect('posts:post_detail', post_id=post_id)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %} Редактировать пост
  {% else %} Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  {% load user_filters %}
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %} Редактировать пост
              {% else %} Новый пост
              {% endif %}
            </div>
          <div class="card-body">
            {% include 'posts/includes/form_errors.html' %}

            <form method="post"
              {% if is_edit %}
                action="{% url 'posts:post_edit' post_id %}"
              {% else %}
                action="{% url 'posts:post_create' %}"
              {% endif %}
              enctype="multipart/form-data"
            >

              {% include 'posts/includes/form_display.html' %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %} Сохранить
                  {% else %} Добавить
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}

{% block title %}
  Лента ваших авторов
{% endblock %}

{% block content %}
  <h1>Лента ваших авторов</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj%}
    {% include 'posts/includes/post_card.html' %}
    <p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </p>
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description|linebreaks }}</p>
  {% for post in page_obj %}
    {% include 'posts/includes/post_card.html' %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  <h1>Последние обновления на сайте</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj%}
    {% include 'posts/includes/post_card.html' %}
    <p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </p>
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/like.html
{% extends 'base.html' %}

{% block title %}
  Понравившиеся вам посты
{% endblock %}

{% block content %}
  <h1>Понравившиеся вам посты</h1>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj%}
    {% include 'posts/includes/post_card.html' %}
    <p>
      {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
      {% endif %}
    </p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Пост {{ post }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ post.group.title }}
            <a href="{% url 'posts:group_list' post.group.slug %}">
              все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">
            все посты пользователя
          </a>
        </li>
      </ul>
    </aside>

    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|linebreaks }}</p>
      {% if user.username == post.author.username %}
        <a class="btn btn-primary"
           href="{% url 'posts:post_edit' post.id %}">
              Редактировать запись
        </a>
      {% endif %}

      {% include 'posts/includes/like_button.html' %}

      {% include 'posts/includes/add_comment.html' %}
    </article>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
    <div class="mb-5">
      <h1>Все посты пользователя {{ author.get_full_name }}</h1>
      <h3>Всего постов: {{ author.posts.count }} </h3>
      {% if following %}
        <a
          class="btn btn-lg btn-light"
          href="{% url 'posts:profile_unfollow' author.username %}" role="button"
        >
          Отписаться
        </a>
      {% else %}
          <a
            class="btn btn-lg btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
          >
            Подписаться
          </a>
       {% endif %}
      {% for post in page_obj%}
        {% include 'posts/includes/post_card.html' %}
        <p>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">
                все записи группы
            </a>
          {% endif %}
        </p>
      {% endfor %}

      {% include 'posts/includes/paginator.html' %}
    </div>
{% endblock %}